# Generated by Django 4.1.2 on 2022-10-31 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_naplo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolgozat',
            name='feladatok',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='dolgozat',
            name='matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='dolgozat',
            name='tanulok',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=1), size=None),
        ),
    ]
