# Generated by Django 4.1.2 on 2022-11-01 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_naplo', '0002_alter_dolgozat_feladatok_alter_dolgozat_matrix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dolgozat',
            name='M',
        ),
        migrations.RemoveField(
            model_name='dolgozat',
            name='N',
        ),
        migrations.AddField(
            model_name='dolgozat',
            name='feladatmaximumok',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
            preserve_default=False,
        ),
    ]
