# Generated by Django 4.1.2 on 2022-11-12 14:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_naplo', '0003_remove_dolgozat_m_remove_dolgozat_n_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolgozat',
            name='feladatmaximumok',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=None),
        ),
        migrations.AlterField(
            model_name='dolgozat',
            name='matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=-1), size=None), size=None),
        ),
    ]
