# Generated by Django 4.0.2 on 2024-06-09 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_naplo', '0004_alter_dolgozat_feladatmaximumok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolgozat',
            name='sulyvektor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=1), default=[], size=None),
            preserve_default=False,
        ),
    ]
