# Generated by Django 4.0.2 on 2024-06-13 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_naplo', '0005_dolgozat_sulyvektor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lezaras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now=True)),
                ('jegy', models.SmallIntegerField(default=0)),
                ('szoveg', models.TextField(default='-')),
                ('csoport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('tanulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lezárás',
                'verbose_name_plural': 'Lezárások',
            },
        ),
    ]
