# Generated by Django 4.0.2 on 2025-01-25 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_naplo', '0006_lezaras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Téma',
                'verbose_name_plural': 'Témák',
            },
        ),
        migrations.AddField(
            model_name='dolgozat',
            name='kotelezo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dolgozat',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_naplo.tema'),
        ),
    ]
