# Generated by Django 3.2.6 on 2021-08-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bigyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szoveg', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bigyo',
                'verbose_name_plural': 'Bigyók',
            },
        ),
    ]
