# Generated by Django 4.0.2 on 2022-02-04 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('APP', '0002_felhasznalo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csoport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('tanar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tanár-Csoport reláció',
                'verbose_name_plural': 'Tanár-Csoport relációk',
            },
        ),
        migrations.DeleteModel(
            name='Felhasznalo',
        ),
    ]
