# Generated by Django 4.0.2 on 2022-02-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_temakor_sorrend_alter_kituzes_ido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hf',
            name='mentoralando',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hf',
            name='url',
            field=models.URLField(default='https://github.com/'),
        ),
    ]
