# Generated by Django 4.0.2 on 2022-02-04 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP', '0003_tanit_delete_felhasznalo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL)),
                ('mentoree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoree', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorálás',
                'verbose_name_plural': 'Mentorálás',
            },
        ),
    ]
