# Generated by Django 4.0.2 on 2022-03-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_hf_mentoralando_alter_hf_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='git',
            options={'verbose_name': 'Git-profil', 'verbose_name_plural': 'Git-profilok'},
        ),
    ]
