# Generated by Django 4.0.2 on 2022-02-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_mentoral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feladat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Feladat',
                'verbose_name_plural': 'Feladat',
            },
        ),
        migrations.CreateModel(
            name='Temakor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Témakör',
                'verbose_name_plural': 'Témakörök',
            },
        ),
        migrations.CreateModel(
            name='Tartozik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feladat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoree', to='APP.feladat')),
                ('temakor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='APP.temakor')),
            ],
            options={
                'verbose_name': 'Témakör-Feladat reláció',
                'verbose_name_plural': 'Témakör-Feladat relációk',
            },
        ),
    ]
