# Generated by Django 4.0.2 on 2022-02-04 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP', '0005_feladat_temakor_tartozik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tartozik',
            name='feladat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.feladat'),
        ),
        migrations.AlterField(
            model_name='tartozik',
            name='temakor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.temakor'),
        ),
        migrations.CreateModel(
            name='Kituzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ido', models.DateTimeField()),
                ('feladat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.feladat')),
                ('tanar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitűzés',
                'verbose_name_plural': 'Kitűzések',
            },
        ),
    ]
