# Generated by Django 4.0.2 on 2022-02-04 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP', '0006_alter_tartozik_feladat_alter_tartozik_temakor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatarido', models.DateTimeField()),
                ('mentoralando', models.BooleanField()),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kituzes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.kituzes')),
            ],
            options={
                'verbose_name': 'Házi feladat',
                'verbose_name_plural': 'Házi feladatok',
            },
        ),
    ]
