# Generated by Django 4.0.2 on 2022-04-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_auto_20220314_2019'),
        ('APP', '0006_alter_git_platform'),
    ]

    operations = [
    ]
