# Generated by Django 4.0.2 on 2022-10-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_merge_0005_auto_20220314_2019_0006_alter_git_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='hf',
            name='allapot',
            field=models.CharField(choices=[('NINCS_BIRALAT', 'NINCS_BIRALAT'), ('NINCS_MO', 'NINCS_MO'), ('NINCS_BIRALAT', 'NINCS_BIRALAT'), ('VAN_NEGATIV_BIRALAT', 'VAN_NEGATIV_BIRALAT'), ('MINDEN_BIRALAT_POZITIV', 'MINDEN_BIRALAT_POZITIV')], default='NINCS_REPO', max_length=50),
        ),
    ]
