# Generated by Django 4.0.2 on 2022-02-04 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_hf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('ido', models.DateTimeField()),
                ('hf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.hf')),
            ],
            options={
                'verbose_name': 'Megoldás',
                'verbose_name_plural': 'Megoldások',
            },
        ),
    ]
