# Generated by Django 4.0.2 on 2022-02-04 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP', '0008_mo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biralat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szoveg', models.TextField()),
                ('itelet', models.CharField(max_length=100)),
                ('kozossegi_szolgalati_orak', models.IntegerField()),
                ('ido', models.DateTimeField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.mo')),
            ],
            options={
                'verbose_name': 'Megoldás',
                'verbose_name_plural': 'Megoldások',
            },
        ),
    ]
