# Generated by Django 4.0.2 on 2022-10-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_hf_allapot'),
    ]

    operations = [
        migrations.AddField(
            model_name='git',
            name='count_of_minden_biralat_pozitiv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='git',
            name='count_of_nincs_biralat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='git',
            name='count_of_nincs_mo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='git',
            name='count_of_nincs_repo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='git',
            name='count_of_van_negativ_biralat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hf',
            name='allapot',
            field=models.CharField(choices=[('NINCS_REPO', 'NINCS_REPO'), ('NINCS_MO', 'NINCS_MO'), ('NINCS_BIRALAT', 'NINCS_BIRALAT'), ('VAN_NEGATIV_BIRALAT', 'VAN_NEGATIV_BIRALAT'), ('MINDEN_BIRALAT_POZITIV', 'MINDEN_BIRALAT_POZITIV')], default='NINCS_REPO', max_length=50),
        ),
    ]
