# Generated by Django 4.0.2 on 2022-02-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_biralat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biralat',
            options={'verbose_name': 'Bírálat', 'verbose_name_plural': 'Bírálatok'},
        ),
        migrations.AddField(
            model_name='feladat',
            name='nev',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temakor',
            name='nev',
            field=models.CharField(max_length=255),
        ),
    ]
