# Generated by Django 4.1.2 on 2023-06-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_git_count_of_mentoraltnal_minden_biralat_pozitiv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haladek_kerelem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now=True)),
                ('tipus', models.CharField(choices=[('NINCS_REPO', 'NINCS_REPO'), ('NINCS_MO', 'NINCS_MO'), ('NINCS_BIRALAT', 'NINCS_BIRALAT'), ('VAN_NEGATIV_BIRALAT', 'VAN_NEGATIV_BIRALAT'), ('MINDEN_BIRALAT_POZITIV', 'MINDEN_BIRALAT_POZITIV')], default='NINCS_REPO', max_length=64)),
                ('targy', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('url', models.URLField(blank=True, max_length=256, null=True)),
                ('nap', models.IntegerField()),
                ('hf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.hf')),
            ],
            options={
                'verbose_name': 'Haladékkérelem',
                'verbose_name_plural': 'Haladékkérelmek',
            },
        ),
        migrations.CreateModel(
            name='Egyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now=True)),
                ('kreta', models.BooleanField()),
                ('hf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.hf')),
            ],
            options={
                'verbose_name': 'Egyes',
                'verbose_name_plural': 'Egyesek',
            },
        ),
    ]
