# Generated by Django 4.0.2 on 2022-02-04 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('APP', '0010_alter_biralat_options_feladat_nev_alter_temakor_nev'),
    ]

    operations = [
        migrations.AddField(
            model_name='kituzes',
            name='group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
