# Generated by Django 4.2.5 on 2023-11-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_hazicsoport'),
    ]

    operations = [
        migrations.AddField(
            model_name='feladat',
            name='temai',
            field=models.ManyToManyField(to='APP.temakor'),
        ),
    ]
