# Generated by Django 4.0.2 on 2022-02-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_git'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('hf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.hf')),
            ],
            options={
                'verbose_name': 'Repó',
                'verbose_name_plural': 'Repók',
            },
        ),
    ]
