# Generated by Django 4.0.2 on 2022-02-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_repo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mo',
            name='hf',
        ),
        migrations.RemoveField(
            model_name='mo',
            name='url',
        ),
    ]
