# Generated by Django 4.0.2 on 2024-03-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_feladat_temai'),
    ]

    operations = [
        migrations.AddField(
            model_name='kituzes',
            name='hatarido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feladat',
            name='temai',
            field=models.ManyToManyField(to='APP.Temakor'),
        ),
    ]
