# Generated by Django 4.0.2 on 2024-03-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_kituzes_hatarido_alter_feladat_temai'),
    ]

    operations = [
        migrations.AddField(
            model_name='haladek_kerelem',
            name='biralat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.biralat'),
        ),
        migrations.AddField(
            model_name='haladek_kerelem',
            name='elbiralva',
            field=models.CharField(choices=[('elfogadott', 'elfogadott'), ('elutasitott', 'elutasitott'), ('fuggo', 'fuggo')], default='fuggo', max_length=64),
        ),
        migrations.AlterField(
            model_name='haladek_kerelem',
            name='tipus',
            field=models.CharField(choices=[('hianyzas', 'hianyzas'), ('mentoralas', 'mentoralas'), ('egyeb', 'egyeb')], default='egyeb', max_length=64),
        ),
    ]
