# Generated by Django 4.0.2 on 2022-02-05 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_remove_mo_hf_remove_mo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mo',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.repo'),
        ),
    ]
