# Generated by Django 4.0.2 on 2022-02-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_mo_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mo',
            name='szoveg',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
