# Generated by Django 4.0.2 on 2024-03-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_haladek_kerelem_biralat_haladek_kerelem_elbiralva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='haladek_kerelem',
            name='valasz',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
