# Generated by Django 4.0.2 on 2024-03-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_haladek_kerelem_valasz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haladek_kerelem',
            name='valasz',
            field=models.TextField(default='-'),
        ),
    ]
