# Generated by Django 4.0.2 on 2024-06-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0017_alter_haladek_kerelem_valasz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haladek_kerelem',
            name='valasz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
