# Generated by Django 4.0.2 on 2022-02-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0017_rename_felhasznalo_hf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo',
            name='repo',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='APP.repo'),
            preserve_default=False,
        ),
    ]
