# Generated by Django 4.0.2 on 2022-02-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_alter_mo_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biralat',
            name='kozossegi_szolgalati_orak',
            field=models.DurationField(),
        ),
    ]
