# Generated by Django 4.0.2 on 2024-06-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_alter_haladek_kerelem_valasz'),
    ]

    operations = [
        migrations.AddField(
            model_name='egyes',
            name='suly',
            field=models.FloatField(default=1),
        ),
    ]
