# Generated by Django 4.0.2 on 2025-01-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0019_egyes_suly'),
    ]

    operations = [
        migrations.AddField(
            model_name='git',
            name='commithistory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='git',
            name='github_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
