# Generated by Django 3.2.9 on 2022-02-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0019_alter_biralat_kozossegi_szolgalati_orak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo',
            name='ido',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
