# Generated by Django 4.0.2 on 2022-02-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0020_alter_mo_ido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biralat',
            name='ido',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
