# Generated by Django 4.0.2 on 2025-01-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0020_git_commithistory_git_github_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biralat',
            name='ido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='egyes',
            name='datum',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='haladek_kerelem',
            name='datum',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kituzes',
            name='ido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mo',
            name='ido',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
