# Generated by Django 4.0.2 on 2025-01-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0021_alter_biralat_ido_alter_egyes_datum_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tartozik',
        ),
    ]
