# Generated by Django 4.0.2 on 2022-02-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0021_alter_biralat_ido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biralat',
            name='kozossegi_szolgalati_orak',
            field=models.IntegerField(),
        ),
    ]
