# Generated by Django 4.0.2 on 2025-01-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0022_delete_tartozik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kampany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('graphviz', models.TextField()),
                ('svg', models.TextField()),
                ('feladatai', models.ManyToManyField(blank=True, to='APP.Feladat')),
            ],
            options={
                'verbose_name': 'Kampány',
                'verbose_name_plural': 'Kampányok',
            },
        ),
    ]
