# Generated by Django 4.0.2 on 2022-02-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0022_alter_biralat_kozossegi_szolgalati_orak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biralat',
            old_name='kozossegi_szolgalati_orak',
            new_name='kozossegi_szolgalati_percek',
        ),
    ]
