# Generated by Django 4.0.2 on 2022-02-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0023_rename_kozossegi_szolgalati_orak_biralat_kozossegi_szolgalati_percek'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='ido',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
