# Generated by Django 4.0.2 on 2025-10-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0023_kampany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egyes',
            name='suly',
            field=models.FloatField(default=0.5),
        ),
    ]
